apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: database
  template:
    metadata:
      labels:
        service: database
    spec:
      containers:
      - name: database
        image: postgres
        imagePullPolicy: IfNotPresent
        env:
        - name : POSTGRES_USER
          valueFrom :
            secretKeyRef:
              name : postgres-credentials
              key : user 
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password

        - name: POSTGRES_DB
          value: relate
          
        volumeMounts:
          - name: database-volume-mount
            mountPath: /var/lib/database/data

      volumes:
      - name: database-volume-mount
        persistentVolumeClaim:
          claimName: database-pvc
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    service: database
spec:
  selector:
    service: database
  type: ClusterIP
  ports:
  - port: 5432
