apiVersion: networking.k8s.io/v1beta1

kind: Ingress
metadata:
  name: my-ingress
  annotations:
spec:
  rules:
  - host: relate.me
    http:
      paths:
      - backend:
          serviceName: django
          servicePort: 8000

     
