apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: relate-ingress
  annotations:
spec:
  rules:
  - host: {{.Values.ingress.host}}
    http:
      paths:
      - backend:
          serviceName: relate
          servicePort: 8000

     
