apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    service: django
spec:
  selector:
    app: django
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    service: database
spec:
  selector:
    service: database
  type: ClusterIP
  ports:
  - port: 5432
