{{- range $element := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $element.name }}
  labels:
    service: {{ $element.name }}
spec:
  selector:
    service: {{ $element.name }}
  type: ClusterIP
  ports:
  - port: {{ $element.port }}
    targetPort: {{ $element.port }}
---
{{- end }}


